service: thumbnail-sbs

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  timeout: 10
  memorySize: 128
  environment:
    THUMBNAIL_SIZE: 128

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Resource: '*'
          Action: 's3:*'

functions:
  thumbnail_sbs:
    handler: handler.thumbnail_sbs
    layers:
      - arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-pillow:1
    events:
      - s3:
          bucket: BUCKETNAME
          event: s3:ObjectCreated:*

plugins:
  - serverless-python-requirements
